frase = 'Curso em video Python'
frase2 = '   Salve Galera   '
print(frase)
print(frase[3])
print(frase[4:17])
print(frase[7:12:2])
print(frase[:10])
print(frase[7:])
print(frase[1::3])
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 18))
print(frase.find('em'))
print('video' in frase)
print(frase.replace('Curso', 'Salve'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase2.split())
print(''.join(frase2))